-- Create users table
USE is_schedulalbe;
DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS (
    NO INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    CRE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPD_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
CHARACTER SET 'utf8'
COLLATE 'utf8_general_ci'
ENGINE = InnoDB;